### ISSUE TITLE
Assertion error in ConnectionBase::read_as_much_as_possible_from_socket_without_blocking

### ISSUE THREAD

**Issue by lokedhs** [SerenityOS/ladybird#116] opened 2022-11-08 12:35 UTC
When attempting to load a web application, I'm getting an assertion error in the above mentioned function and the browser exits:

The problem can be reproduced by loading the following URL: https://kapdemo.dhsdevelopments.com/clientweb2/

```
ResourceLoader: Finished load of: "https://kapdemo.dhsdevelopments.com/clientweb2/compute-queue-worker.js", Duration: 14ms
WebContent: /home/elias/src/ladybird/Build/serenity/AK/TypeCasts.h:42: AK::Detail::CopyConst<InputType, OutputType>& AK::verify_cast(InputType&) [with OutputType = Web::HTML::Window; InputType = JS::Object; Detail::CopyConst<InputType, OutputType> = Web::HTML::Window]: Assertion `is<OutputType>(input)' failed.
ConnectionBase::read_as_much_as_possible_from_socket_without_blocking: recv: Connection reset by peer (errno=104)
ConnectionBase::read_as_much_as_possible_from_socket_without_blocking: recv: Connection reset by peer (errno=104)
ladybird: /home/elias/src/ladybird/Build/serenity/Userland/Libraries/LibIPC/Connection.cpp:170: AK::ErrorOr<AK::Vector<unsigned char> > IPC::ConnectionBase::read_as_much_as_possible_from_socket_without_blocking(): Assertion `false' failed.
Subprocess aborted
FAILED: CMakeFiles/run /home/elias/src/ladybird/Build/CMakeFiles/run 
cd /home/elias/src/ladybird/Build && /usr/bin/cmake -E env SERENITY_SOURCE_DIR=/home/elias/src/ladybird/Build/serenity /home/elias/src/ladybird/Build/ladybird
```

The assertion appears to be the call to `VERIFY_NOT_REACHED()` that is called if there is an error, and the following expression is not true: `error.is_syscall() && error.code() == EAGAIN`

**Comment by rice7th** [comment] 2022-11-20 19:34
Same error here! hope it gets fixed soon

**Comment by xyproto** [comment] 2022-11-23 23:10
I get the same assertion on Arch Linux, when building `ladybird` from the latest commit and just running it:

```
execvp: No such file or directory
VERIFICATION FAILED: false
/build/ladybird/src/ladybird/WebContentView.cpp:615
ConnectionBase::read_as_much_as_possible_from_socket_without_blocking: recv: Connection reset by peer (errno=104)
ConnectionBase::read_as_much_as_possible_from_socket_without_blocking: recv: Connection reset by peer (errno=104)
VERIFICATION FAILED: false
/build/ladybird/src/ladybird/build/serenity/Userland/Libraries/LibIPC/Connection.cpp:170
/usr/bin/ladybird: line 2: 68828 Illegal instruction     (core dumped) SERENITY_SOURCE_DIR=/usr/share/serenity /usr/share/serenity/Base/bin/ladybird
```

The `Connection reset by peer (errno=104)` error:

* Did not appear in commit b8812092b1cb7a1e91e0080b2088ee73187f74bc (from 2022-11-16).
* But it does appear in commit 328af1b54a29b15549467f91c831381e029bc9d2 (from 2022-11-19).

**Comment by BertalanD** [comment] 2022-11-24 07:19
This will be fixed by https://github.com/SerenityOS/serenity/pull/16166.  The crash was caused by the IPC layer not correctly handling the death of the `WebContent` process in some cases. As such, even after the fix lands, the affected website won't load, but at least the `WebContent` crash won't bring down the whole browser GUI.

**Closed** 2022-11-24 13:37 UTC
